[pytest]
markers =
    gate01: Testes do primeiro portão de qualidade
    gate02: Testes do motor de simulação
    gate03: Testes de análise de crédito
    gate04: Testes de documentação
    gate05: Testes de aprovações internas
    gate06: Testes de assinatura eletrônica
    gate07: Testes de faturamento
    gate08: Testes de equipamentos
    smoke_test: Testes rápidos de sanidade
    auth: Testes de autenticação
    pr_blocker: Testes que bloqueiam o Merge do PR
    login: Cenário de login com sucesso
    login_invalido: Cenário de login inválido
    logout: Cenário de logout
    acesso_negado: Cenário de acesso negado
    simulacao: Testes de simulação
    analise_credito: Testes de análise de crédito
    documentacao: Testes de documentação
    fluxo_admin: Testes de fluxo administrativo
    aprovacoes: Testes de aprovações
    faturamento: Testes de faturamento
    assinatura: Testes de assinatura eletrônica
addopts = --headed --browser chromium --alluredir=./allure-results
testpaths = tests