[pytest]
markers =
    gate01: Testes do primeiro portão de qualidade
    gate02: Testes do motor de simulação
    smoke_test: Testes rápidos de sanidade
    auth: Testes de autenticação
    pr_blocker: Testes que bloqueiam o Merge do PR[pytest]
addopts = --headed --browser chromium --alluredir=./allure-results
testpaths = tests